[project]
name = "audiogen"
version = "2025.3.15.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.11",
    "sodatools>=2025.2.16.0",
    "uvicorn[standard]>=0.34.0",
]
